### ISSUE TITLE
Skills logo are not found 

### ISSUE THREAD

**Issue by Vandit-dev** [carrycooldude/Carry-PortFolio#2]
**Describe the bug**
Skill logo are not visible on website there are some errors 

**To Reproduce**
1. Go to 'Website'
2.  Scroll down to 'Skill section '
3.  See error 'skill logo is not visible'

**Expected behavior**
Skill logo have to visible and works perfectly like other.

**Screenshots**
![Screenshot_20230317-001150_Chrome](https://user-images.githubusercontent.com/93773611/225723591-7b099b67-8c6a-47b9-9f02-4c1154b50f7e.jpg)

**Smartphone (please complete the following information):**
 - Device: [ Samsung M31s]
 - OS: [ Android  12]
 - Browser [ Google Chrome]
 - Version [111.0.5563.58 ]

**Comment by carrycooldude** [comment]
Thanks for creating issue @Vandit-dev and thanks for letting me know 
Will update this soon...

**Comment by carrycooldude** [comment]
Done the implemenation
